language: rust
script: cargo test --all-features --all

jobs:
  include:
  - rust: 1.33.0
  - rust: stable
  - rust: beta
  - rust: nightly
  - rust: nightly
    env: TARGET=WASM32  # For job list UI
    install: rustup target add wasm32-unknown-unknown
    script: cargo build --all --target=wasm32-unknown-unknown
