[package]

name = "url"
version = "0.2.36"
authors = [ "Simon Sapin <simon.sapin@exyr.org>" ]

description = "URL parser for Rust"
documentation = "http://servo.github.io/rust-url/url/index.html"
repository = "https://github.com/servo/rust-url"
readme = "README.md"
keywords = ["url", "parser"]
license = "MIT/Apache-2.0"

[features]
query_encoding = ["encoding"]
serde_serialization = ["serde"]

[dependencies.encoding]
version = "0.2"
optional = true

[dependencies.serde]
version = "*"
optional = true

[dependencies]
rustc-serialize = "0.3"
matches = "0.1"
