[package]

name = "url"
version = "1.0.0-dev"
authors = [ "Simon Sapin <simon.sapin@exyr.org>" ]

description = "URL library for Rust, based on the WHATWG URL Standard"
documentation = "http://servo.github.io/rust-url/url/index.html"
repository = "https://github.com/servo/rust-url"
readme = "README.md"
keywords = ["url", "parser"]
license = "MIT/Apache-2.0"

[[test]] name = "form_urlencoded"
[[test]] name = "idna"
[[test]] name = "punycode"
[[test]] name = "tests"
[[test]]
name = "wpt"
harness = false

[dev-dependencies]
rustc-test = "0.1"

[features]
query_encoding = ["encoding"]
heap_size = ["heapsize", "heapsize_plugin"]

[dependencies]
heapsize = {version = ">=0.1.1, <0.4", optional = true}
heapsize_plugin = {version = "0.1.4", optional = true}
encoding = {version = "0.2", optional = true}
serde = {version = ">=0.6.1, <0.8", optional = true}
rustc-serialize = "0.3"
unicode-bidi = "0.2.3"
unicode-normalization = "0.1.2"
matches = "0.1"
